---

- hosts: compute
  become: yes
  tasks:
    - name: disable SELinux
      selinux:
        state: permissive
        policy: targeted

- hosts: compute
  become: yes
  roles:
    - citc_user
    - filesystem
    - ssh
    ##- security_updates
    - ntp
    - sssd
    - lmod
    - packages
    - mpi
    - slurm
    - monitoring
