---

- name: install roles
  hosts: management
  tasks:
    - name: Download required roles
      command: ansible-galaxy install -r requirements.yml
      register: galaxy_result
      changed_when: '"was installed successfully" in galaxy_result.stdout'
      become: false
      delegate_to: localhost

- name: finisher script
  hosts: management
  tasks:
    - name: copy over finisher script
      template:
        src: roles/finalise/templates/finish.py.j2
        dest: /usr/local/bin/finish
        mode: 0755
    - name: set motd
      copy:
        content: |
          ######################

          Welcome to the cluster
          Please now create users and define the number of nodes you want.

          ######################
        dest: /etc/motd

- name: common
  hosts: all
  tags: common
  roles:
    - citc_user
    - filesystem
    - ssh
    - security-updates
    - ntp
    - 389ds
    - sssd
    - python
    - users
    - mysql
    - slurm
    - packer
  tasks:
    - name: copy SSH public keys to slurm account
      copy:
        src: "{{ admin_key_path }}"
        dest: /home/slurm/opc_authorized_keys
        owner: slurm
        group: slurm
        mode: 0600

- name: finalise
  hosts: all
  tags: finalise
  roles:
    - finalise
    - apps
    - webui
    - monitoring
    - clustershell
    - packages
    - devtoolset
    - mpi
    - sos
    - debug-tools
    - lmod
