---

- name: Install roles
  hosts: management
  tasks:
    - name: Download required roles
      community.general.ansible_galaxy_install:
        type: both
        requirements_file: requirements.yml
      become: false
      delegate_to: localhost

- name: Finisher script
  hosts: management
  tasks:
    - name: Copy over finisher script
      ansible.builtin.template:
        src: roles/finalise/templates/finish.py.j2
        dest: /usr/local/bin/finish
        mode: "0755"
    - name: Set motd
      ansible.builtin.copy:
        content: |
          ######################

          Welcome to the cluster
          Please now create users and define the number of nodes you want.

          ######################
        dest: /etc/motd
        mode: u=rw,g=r,o=r

- name: Common
  hosts: all
  tags: common
  roles:
    - citc_user
    - ldap
    - mysql
    - filesystem
    - slurm
    - packer
    - ssh
    - security_updates
    - ntp
    - sssd
    - distrac_group
    - users
  tasks:
    - name: Copy SSH public keys to slurm account
      ansible.builtin.copy:
        src: "{{ admin_key_path }}"
        dest: /home/slurm/opc_authorized_keys
        owner: slurm
        group: slurm
        mode: "0600"

- name: Finalise
  hosts: all
  tags: finalise
  roles:
    - finalise
    - apps
    - get_secrets
    - webui
    - monitoring
    - packages
    - devtoolset
    - mpi
    - sos
    - debug_tools
    - lmod
