---
- name: Install OpenStack SDK
  ansible.builtin.pip:
    name:
      - python-openstackclient
    virtualenv: /opt/cloud_sdk

- name: Create citc config dir
  ansible.builtin.file:
    path: /home/slurm/.config/openstack/
    state: directory
    owner: slurm
    group: slurm
    mode: o=rwx,g=,o=

- name: Configure OpenStack clouds.yaml
  ansible.builtin.copy:
    src: /home/cloud-user/clouds.yaml
    dest: /home/slurm/.config/openstack/clouds.yaml
    owner: slurm
    group: slurm
    mode: o=rw,g=,o=

- name: Create citc config dir
  ansible.builtin.file:
    path: /root/.config/openstack/
    state: directory
    owner: root
    group: root
    mode: o=rwx,g=,o=

- name: Configure OpenStack clouds.yaml
  ansible.builtin.copy:
    src: /home/cloud-user/clouds.yaml
    dest: /root/.config/openstack/clouds.yaml
    owner: root
    group: root
    mode: o=rw,g=,o=

- name: Install startnode support module
  ansible.builtin.copy:
    src: citc_openstack.py
    dest: /opt/cloud_sdk/lib/python3.8/site-packages/citc_cloud.py
    mode: u=rw,g=r,o=r
