---
- name: Prepare
  hosts: all
  roles:
    - mysql
  tasks:
    - name: make shared mount point
      file:
        path: /mnt/{{ filesystem_mount_point }}
        state: directory
        mode: a=rw,o+x
    - name: make shared /etc dir point
      file:
        path: /mnt/{{ filesystem_mount_point }}/etc
        state: directory
        mode: a=rw,o+x

    - name: startnode config  # Put there by Terraform usually
      copy:
        content: |
          csp:
          cluster_id: example
          ansible_repo: https://github.com/clusterinthecloud/ansible.git
          ansible_branch: 6
        dest: /tmp/startnode.yaml
        mode: u=rw,g=r,o=r

    - name: make ansible config dir
      file:
        path: /etc/ansible
        state: directory
        mode: a=rw,o+x
    - name: make ansible facts dir
      file:
        path: /etc/ansible/facts.d
        state: directory
        mode: a=rw,o+x
    - name: create local citc.fact file  # Put there by Terraform usually
      copy:
        # Choose one CSP for now, based on Python package installation speed
        # TODO parameterise on CSP
        content: |
          {"csp":"google", "fileserver_ip":"10.0.0.1", "mgmt_hostname":"mgmt"}
        dest: /etc/ansible/facts.d/citc.fact
        mode: u=rw,g=r,o=r
