---
name: CI

on:  # yamllint disable-line rule:truthy
  - push
  - pull_request

jobs:
  test_python:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install oci pytest-mock pytest-asyncio pyyaml mypy \
                      requests_mock google-api-python-client google-auth boto3 \
                      "boto3-stubs[ec2,route53]" \
                      https://github.com/clusterinthecloud/python-citc/releases/download/0.3.11/citc-0.3.11-py3-none-any.whl
      - name: Test with pytest
        run: pytest
      - name: Type check
        run: |
          mypy roles/slurm/files/citc_aws.py roles/slurm/files/citc_gcp.py roles/slurm/files/citc_oci.py

  yaml_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: YAML lint
        run: |
          yamllint *.yml group_vars roles

  ansible_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'ansible ~= 8.0' 'ansible-lint'
      - name: Ansible lint
        run: |
          ansible-lint --offline management.yml compute.yml nfsserver.yml

  test_roles:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        role: [citc_user, users, ssh, lmod, slurm, monitoring, packer, webui]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: Install Molecule
        run: |
          python -m pip install 'ansible ~= 8.0' 'ansible-lint' 'molecule-plugins[podman]'
      - name: Test role
        run: |
          cd roles/${{ matrix.role }}
          molecule test --all --driver-name podman
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
