---
name: CI

on: [push, pull_request]

jobs:
  test_python:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install oci pytest-mock pytest-asyncio pyyaml mypy \
                      requests_mock google-api-python-client google-auth boto3 \
                      "boto3-stubs[ec2,route53]" \
                      https://github.com/clusterinthecloud/python-citc/releases/download/0.3.10/citc-0.3.10-py3-none-any.whl
      - name: Test with pytest
        run: pytest
      - name: Type check
        run: |
          mypy roles/slurm/files/citc_aws.py roles/slurm/files/citc_gcp.py roles/slurm/files/citc_oci.py

  ansible_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'ansible<2.10,>=2.9' 'ansible-lint<6.0.0'
      - name: Ansible lint
        run: |
          ansible-lint --offline management.yml compute.yml nfsserver.yml

  test_roles:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        role: [citc_user, ssh, lmod, slurm, monitoring, packer, webui]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: install python3-docker
        run: sudo apt-get install python3-docker
      - name: Install Molecule
        run: |
          python -m pip install 'ansible<2.10,>=2.9' 'ansible-lint<6.0.0' 'molecule[podman,docker]==3.4.1'
      - name: Test role
        run: |
          cd roles/${{ matrix.role }}
          molecule test --all --driver-name docker
